# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: f1365d7533a35145f1f19f86e71a0cb95b6d468446beeff8210d2d926732da58aeea21576e1bb7de5b0c63e16d60ace0e875f987c0bdaef222c66483b834efe1

test:
  secret_key_base: 344548a9eb8410a82b1ad09d8c6e2870f1b33e52a469183e9de994d214551cd6611ee9ba6ddfa5211bb3342b71377e84dad1d6cd8a0fabf206f44cac305c6780

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
